#!/bin/bash

target="$3"
homeDir=$(dirname "$0")

if [ "$target" = "/" ]; then
	for eachFile in "$homeDir"/*.pkg; do
		if ! installer -pkg "$eachFile" -target "$target"; then
			exit $?
		fi
	done
fi
exit 0
